name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Build image and project
        run: |
          docker build -t builder:latest .
          docker run -t -v $PWD:/mnt builder:latest bash -c "cd /mnt && ls -lsa"
          docker run -t -v $PWD:/mnt builder:latest bash -c "build.sh"
          
